### ISSUE TITLE
Set up Google Search Console for our sites

### ISSUE THREAD

**Issue by chasenlehara** [donejs/developer-relations#52]

**Comment by chasenlehara** [comment]
Set it up for Bitovi.com, CanJS.com, DoneJS.com, and StealJS.com; still need to:

- [ ] [Set up Google Analytics for DocumentCSS.com](https://github.com/bitovi/documentcss/issues/62)
- [ ] [Set up Google Analytics for DocumentJS.com](https://github.com/bitovi/documentjs/issues/146)
- [x] Fix the tracking code for EmbeddedJS.com
- [x] Fix the tracking code for jQueryPP.com
- [x] [Set up Google Analytics for FuncUnit.com](https://github.com/bitovi/funcunit/issues/215)

**Comment by chasenlehara** [comment]
Update:

- I got EmbeddedJS.com, FuncUnit.com, and jQueryPP.com set up correctly.
- I updated Google Analytics on JavaScriptMVC.com but then realized that someone already set up Search Console for it (so I need to ask for access).
- I filed separate issues for setting up Google Analytics for DocumentCSS and DocumentJS.
