### ISSUE TITLE
Streamable Web Apps Presentation

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/developer-relations#54]
# Justin

- [ ] - Finish Outline
   - [x] - Introduction
   - [x] - Stream + NDJSON + Fetch
   - [ ] - PUSH
   - [ ] - Incremental Render
   - [ ] - Conclusion

## Jamie

- [x] - `1` 
   - show size perspective.
   - rid of question mark.
   - kayaker gradient 
- [x] - `2` - rough draft
- [x] - `3-4` - add more rocks before, remove the rocks after
- [ ] - `5-6` - animate the streaming part to show "chunking"
- [x] - `8` floating water
- [ ] - `10` JUSTIN - take `5-6` animation and put it here 
- [x] - `21` - Fix the line issue
- [x] - `8,21` - perspective
- [x] - `28` - make it look more like a waterfall ... rocks + rapids

### Stream + NDJSON + Fetch

- [ ] - Which browsers support this technique? (Chrome, Safari)? (Bianca)
- [ ] -  What databases have good support for this: (Bianca)
   - [x] - Postgres
   - [x] - Mongo (maybe create small example?)
        https://glitch.com/edit/#!/join/d35df473-e855-43d8-a260-e9d32a4cd29a
- [x] - Performance Analysis ([spreadsheet](https://github.com/donejs/developer-relations/issues/54#issuecomment-317522884))
   - [x] - 1st record and last record times across the following axes: (32 combinations)
      - With the technique and without the technique
      - Retrieving 50 and 500 records
      - Postgress returning every 50 and 500 record
      - Internet speeds:
         - Fast throughput vs slow throughput
         - Fast latency vs slow latency
  - [x] - Capture video of best and worst performers ([here](https://github.com/donejs/developer-relations/issues/54#issuecomment-317539812))
- [ ] - Library performance (Bianca)
   - [ ] - How does a react app perform at 100 and 500 records as each record is being added?  Measure the cost of adding one record and the time it takes to update the DOM.
- [ ] - Library support 
   - [ ] - What frameworks / libraries can work with streams?
      - [ ] - Dash?
      - [ ] - Vue?

### HTTP/2 PUSH

- [x] - Which browsers support this technique? (Chome, Safari, looks like edge)?
  - Chrome, Safari, Edge, and Firefox support HTTP2 and PUSH.
- [x] - Performance Analysis ([spreadsheet](https://docs.google.com/spreadsheets/d/1h2dpiwCOYpmEY1Dd1T_AaSW9r766Rtz1dVC0MFm2qrU/edit?usp=sharing))
   - [x] - "JavaScript fully loaded" times across the following axes:
      - With push, without push, and without push but using a CDN
      - 50k of JS vs 500k of JS
      - A single JS asset, or 5 assets.
      - Internet speeds (it may not be possible to mix A and B with C).
         - A. Fast throughput vs slow throughput
         - B. Fast latency vs slow latency
         - C. A nearby consumer and a consumer far away
   - [x] - Capture video of best and worst performers ([here](https://github.com/donejs/developer-relations/issues/54#issuecomment-317024358))
- [x] - Build something for StealJS to be easily able to push packages. ([code examples](https://github.com/stealjs/steal-push#express))
   - [ ] - Get some example code in presentation.
- [x] - Library support .. do any build tools give you useful information?
   - [x] - StealJS **Yes**, using the [bundleManifest](https://stealjs.com/docs/steal-tools.BuildOptions.html) option.
   - [x] - Webpack **No** ([issue](https://github.com/webpack/webpack/issues/1223))

### Incremental Rendering

- [x] - Make it work with AJAX requests

**Comment by justinbmeyer** [comment]
@bgando / @matthewp I added a task around capturing videos for the best and worst performers (biggest deltas). It will probably be useful if I can show the comparisons side by-side, so make the videos about 2x as tall as they are wide.  

For example, I could show:

- NDJSON Streaming 500 records of a 250k data set, on a 3g connection

VS

- SINGLE RESPONSE of 500 records of a 250k data set, on a 3g connection


Also, the app might look as simple as a bunch of very short rows, each with their id.  Similar to:


<img width="178" alt="streamable_web_apps_v2-justin" src="https://user-images.githubusercontent.com/78602/28233235-0d9d11d2-68bb-11e7-8efc-b53d74d386b6.png">

But where you might see ~60 of the 500 rows instead of ~7

**Comment by justinbmeyer** [comment]
@matthewp I'm thinking instead of react, maybe lets just get a "basic" app working like:

```js
module.exports = {
        // what is `createState` for?
	createState: function(request){
		return {};
	},
	render: function(document, state) {
		document.innerHTML = `
		    <div id='sidebar'>Pet Store <div id='cartCount'></div></div>
		    <div id='products'></div>`;

		async function listProducts(){
			var response = await fetch('/products.ndjson');
			var productsEl = document.getElementById('products');
			for await (const product of ndjsonStream(response.body) ) {
				var productEl = `<div>{product.name}</div>`;
				productsEl.appendChild(productEl)
			}
		}
		listProducts();

		fetch('/cartCount').then(function(response){
			return response.json();
		}).then(function(data){
			document.getElementById('cartCount').innerHTML = data.value;
		});
	}
};
```

I'd like to show how to setup something like this with `done-ssr`.  I 'think' we made this work with the existing SSR.  Can you give some sample code of how something like this could be setup to work?  Thanks!

**Comment by matthewp** [comment]
I can create an example app project like this, I agree that it's a good way to go. Would look like:

```js
var ndjsonStream = require('can-ndjson-stream');

module.exports = function(request){
	document.body.innerHTML = `
		<div id='sidebar'>Pet Store <div id='cart-count'></div></div>
		<div id='products'></div>`;

	async function listProducts(){
		var response = await fetch('/api/product');
		var productsEl = document.getElementById('products');
		for await (const product of ndjsonStream(response.body) ) {
			var productEl = `<div>${product.name}</div>`;
			productsEl.appendChild(productEl);
		}
	}
	listProducts();

	fetch('/api/cart').then(function(response){
		return response.json();
	}).then(function(data){
		document.getElementById('cart-count').innerHTML = data.value;
	});
};
```

**Comment by justinbmeyer** [comment]
How does re-attachment happen?

**Comment by matthewp** [comment]
Chrome devtools lets you adjust latency and throughput independently.

<img width="505" alt="screen shot 2017-07-18 at 12 58 46 pm" src="https://user-images.githubusercontent.com/361671/28333738-ddf9cefc-6bc6-11e7-9f3e-830a4044bd3c.png">

**Comment by matthewp** [comment]
I've collected the data on HTTP2 performance. You can view the [spreadsheet here](https://docs.google.com/spreadsheets/d/1h2dpiwCOYpmEY1Dd1T_AaSW9r766Rtz1dVC0MFm2qrU/edit?usp=sharing).

High level observations:

* CDN does better than PUSH in most situations *but*:
  * CDN has the biggest advantage when both latency and throughput are poor.
  * PUSH does better when throughput and latency are good.
  * PUSH does better when latency is good and the user is far away.
  * CDN Does better when latency is poor and user is far away.

**Comment by matthewp** [comment]
I've uploaded 3 videos which show some faster and slower examples from [the data](https://docs.google.com/spreadsheets/d/1h2dpiwCOYpmEY1Dd1T_AaSW9r766Rtz1dVC0MFm2qrU/edit#gid=0).

The datacenter for these tests is in San Francisco.

# Fast - 5 Files,  50k gzipped total,  750k throughput 2ms latency, from Singapore, PUSH

[link](https://drive.google.com/open?id=0B09kZkWwiRDvN0Y2RmlMNnJ4NDQ)

# Fast - 1 File, 50k gzipped total, 30mb throughput 2ms latency, from Kentucky, CDN

[link](https://drive.google.com/open?id=0B09kZkWwiRDvRkZKRjRTeDlEcDg)

# Slow - 5 files, 750k throughput 300k latency, from Singapore, No PUSH

[link](https://drive.google.com/open?id=0B09kZkWwiRDveDA1NnRJMkk4Nkk)

**Comment by matthewp** [comment]
NDJSON data set is here: https://docs.google.com/spreadsheets/d/1_uO79zTYfPwfv3wcOp8xuYTx19KBdw7xp-4RplWnb34/edit#gid=0

Biggest things I noticed:

* NDJSON is a huge win when there is a large dataset and poor throughput.
* NDJSON is a win when latency is low.

**Comment by matthewp** [comment]
# NDJSON Videos

These videos show the difference between using NDJSON vs JSON at 500 records, streaming 1 at a time with 750k throughput and 2ms latency.

* [NDJSON](https://drive.google.com/open?id=0B09kZkWwiRDvd0NFZ3JmQUlNYVE)
* [JSON](https://drive.google.com/open?id=0B09kZkWwiRDvNWZzWHIzNW1xNVU)

**Comment by justinbmeyer** [comment]
Can you make the CSS so most of the 500 fit in the page? 15 columns of 30 items maybe.

**Comment by matthewp** [comment]
i'm going to try.

**Comment by matthewp** [comment]
![screen shot 2017-07-25 at 9 51 11 am](https://user-images.githubusercontent.com/361671/28575340-a3fe3ba4-711e-11e7-94ff-34b2b97f32fa.png)

**Comment by matthewp** [comment]
I'm recalculating the numbers using this sql query to slow it down:

```js
var COUNT = 500;

var cc = `
	SELECT t.*
	FROM (
		SELECT *, row_number() OVER(ORDER BY id ASC) AS row
		FROM todos
	) t
	WHERE t.row % 500 = 0
	limit ${COUNT}
`;
```

**Comment by matthewp** [comment]
# Complex query

I created two new videos using the above query. The spreadsheet is [here](https://docs.google.com/spreadsheets/d/1_uO79zTYfPwfv3wcOp8xuYTx19KBdw7xp-4RplWnb34/edit#gid=253076054).

The times are below:

| NDJSON - First Record | NDJSON - Last Record | JSON   |
|-----------------------|----------------------|--------|
| 140.57                | 509.05               | 535.36 |

## Videos

* [NDJSON](https://drive.google.com/open?id=0B09kZkWwiRDvZnN5QU5sWE5nQ00)
* [JSON](https://drive.google.com/open?id=0B09kZkWwiRDvZEloeXJseGlVSkU)

**Comment by bgando** [comment]
![image](https://user-images.githubusercontent.com/3348231/28600864-699d7374-717a-11e7-8226-2bbf5b4f27af.png)
[Sauce Labs](https://saucelabs.com/u/can-ndjson-stream)

**Comment by matthewp** [comment]
I'm going to make a branch of [donejs-streaming-product-page](https://github.com/donejs/donejs-streaming-product-page) that uses basic HTML and provide a sample as asked for [here](https://github.com/donejs/developer-relations/issues/54#issuecomment-315503258).

**Comment by matthewp** [comment]
[This is a code sample](https://github.com/donejs/donejs-streaming-product-page/blob/160bfe17743d39de4bb6ec6b193a59827f75f673/src/index.js) a project using basic HTML.

**Comment by bgando** [comment]
[Vue.js code sample](https://vue-js-ndjson.glitch.me)
