### ISSUE TITLE
Create Bus Tracker Recipe for Chicago Meetup

### ISSUE THREAD

**Issue by bgando** [donejs/developer-relations#67]
Goal: Create a fun bus tracking CanJS recipe for the Chicago Meetup.

- [x] Check if CTA API will work for this project
  - [X] Does it give the correct data to add a route to google maps
      probably will need to make multiple requests but has the right data
  - [X] Is it rate-limited? If so, by how much?
By default, the Bus Tracker API has a transaction limit of 10,000 transactions/day, but you can ask to increase that limit, which will be evaluated on a case-by-case basis.
  - [X] Will is work with CORs in a jsbin?
  jsbin can be set to http, and then you can use http://cors-anywhere.herokuapp.com/ to get around the CORs issue
- [x] Create the app, balancing simplicity with features that are fun
- [ ] Organize the code so that it can be built out in sequential way
- [ ] Create written recipe so that people can follow on their own

**Comment by bgando** [comment]
@justinbmeyer, do you have a target level for this? Are you expecting mostly beginners?

**Comment by justinbmeyer** [comment]
Beginners

**Comment by bgando** [comment]
https://jsbin.com/diqokat/edit (with a function)
https://jsbin.com/tejapec/edit (with can-component)

**Comment by bgando** [comment]
https://jsbin.com/bewapo/edit (with streams)

**Comment by justinbmeyer** [comment]
Adri's : https://jsbin.com/fuliwa/edit?html,js,output
