### ISSUE TITLE
Epoch 1 Survey Questions

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/developer-relations#77]
# CANJS 

- [x] - [Support JSX-like template syntax](https://github.com/canjs/canjs/issues/3569)
- [X] - [Dynamic and late-mounting custom elements](https://github.com/canjs/can-stache/issues/360)
- [x] - [Create an API for can-element + can-observe and use in guides and recipes (Kevin)](https://github.com/canjs/canjs/issues/3570)
- [x] - [Streamy VMs](https://github.com/canjs/canjs/issues/3324) (Justin)
- [x] - [Expanded Types and Required Properties (Kevin)](https://github.com/canjs/can-define/issues/287)
- [x] - [Form guide + converters](https://github.com/canjs/canjs/issues/3708) (Justin)
- [x] - [Add links to additional resources in each package’s docs](https://github.com/canjs/canjs/issues/3713)
- [x] - [Routing Guide](https://github.com/canjs/can-route/issues/122)
- [x] - [Allow properties to be defined with decorators](https://github.com/canjs/can-define/issues/190)

# STEAL 

-  [x] [can-import with the slim build](https://github.com/stealjs/steal-tools/issues/861#issuecomment-335259777)
- [x] [Improved plugin/extension writing guide](https://github.com/stealjs/stealjs/issues/83)
- [x] [continuous build guide and performance](https://github.com/stealjs/steal-tools/issues/884)
- [x] [tree-shaking](https://github.com/stealjs/rfcs/issues/8)
- [x] [Remove automatic main loading](https://github.com/stealjs/rfcs/issues/7)
- [x] [Support babel-preset-env](https://github.com/stealjs/steal/issues/1277)
- [x] [Allow transpiling module formats other than ESM](https://github.com/stealjs/steal/issues/1276)

# DONEJS 

- [x] [SSR Tips and Tricks guide](https://github.com/donejs/donejs/issues/1049)
- [x] [Add an ecosystem/generators/plugins page](https://github.com/donejs/donejs/issues/682)
- [x] [Baseline PWA support](https://github.com/donejs/donejs/issues/734)
- [x] [A better console for --develop](https://github.com/donejs/done-serve/issues/22)
- [x] [Add docs for customizing the generator templates](https://github.com/donejs/generator-donejs/issues/140)
- [x] [Improvements to debugging zone issues](https://github.com/donejs/donejs/issues/1048) 
- [x] [Improve live-reload performance](https://github.com/donejs/donejs/issues/1014) 
- [x] [Scaffolding](https://github.com/donejs/donejs/issues/1050) (Justin)
